---
title: "tasa final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(scales)
library(lubridate)
library(ggrepel)
library(RColorBrewer)
library(extrafont)
library(hrbrthemes)
library(ggridges)

library(sysfonts)

theme_set(theme_minimal())

df <- readRDS(file = "data/df_dias_cdt_RDS")

df$Month <- factor(df$Month,
                   levels = c("Ene", "Feb", "Mar", "Abr", "May", "Jun",
                              "Jul", "Ago", "Sept", "Oct", "Nov", "Dic"))

df$descripcion <- factor(df$descripcion,
                         levels = c("A 30 Dias", "A 60 Dias", "A 90 Dias",
                                    "A 120 Dias", "A 180 Dias", "A 360 Dias"))

df$Wday <- factor(df$Wday,
                       levels = c("Lunes", "Martes", "Miércoles", "Jueves",
                                  "Viernes"))

df_2020 <- df %>% 
  filter(Year == "2020") %>% 
  arrange(fechacorte)


df_2019 <- df |> 
  filter(Year == "2019") %>% 
  arrange(fechacorte)


df_2021 <- df %>% 
  filter(Year == "2021") %>% 
  arrange(fechacorte)
```

---------------Barplots------------------------
```{r}
# Barplot Entidad por Mes
df_2020 %>% 
  filter(fct_lump(nombreentidad, 5) != "Other") |> 
  group_by(nombreentidad, Month) %>%
  summarise(count = n(),
            .groups = "drop") %>% 
  ggplot(aes(count, reorder_within(nombreentidad, count, Month))) +
  geom_col(fill = "cadetblue4", width = 0.5) +
  scale_y_reordered() +
  facet_wrap(~Month, scales = "free_y")


# Barplot Entidad por Weekday
df_2020 %>% 
  filter(fct_lump(nombreentidad, 5) != "Other") %>% 
  group_by(nombreentidad, Wday) %>%
  summarise(count = n(),
            .groups = "drop") %>% 
  ggplot(aes(count, reorder_within(nombreentidad, count, Wday))) +
  geom_col(width = 0.5) +
  scale_y_reordered() +
  facet_wrap(~Wday, scales = "free")


# Barplot Entidad por Termino(descripcion)
df_2020 %>% 
  filter(fct_lump(nombreentidad, 5) != "Other") %>% 
  group_by(nombreentidad, descripcion) %>% 
  summarise(count = n(),
            .groups = "drop") %>% 
  mutate(nombreentidad = reorder_within(nombreentidad, count, descripcion)) %>% 
  ggplot(aes(count, nombreentidad, fill = descripcion)) +
  geom_col() +
  scale_y_reordered() +
  scale_fill_brewer(type = "qual", palette = 2) +
  facet_wrap(~descripcion, scales = "free_y") +
  theme(legend.position = "none")

```



Histograms of Monto and Tasa
```{r}
df_2020 |>
  ggplot(aes(monto, fill = Wday)) +
  geom_histogram(show.legend = FALSE) +
  geom_vline(xintercept = mean(df_2020$monto), linetype = 2, alpha = 0.4) +
  scale_x_log10() +
  facet_wrap(~Wday)

df_2020 |>
  ggplot(aes(tasa, fill = Wday)) +
  geom_histogram(show.legend = FALSE) +
  geom_vline(xintercept = mean(df_2020$tasa), linetype = 2, alpha = 0.4) +
  scale_fill_brewer(palette = "Dark2", type = "qual") +
  facet_wrap(~Wday)
```



---------------Lineplots------------------------
```{r}

# Lineplot Avg Tasa in 2020
df_2020 %>% 
  group_by(Month, descripcion) %>% 
  summarise(avg_tasa = mean(tasa),
            avg_monto = mean(monto),
            sd_tasa = sd(tasa),
            .groups = "drop") %>% 
  ggplot(aes(Month, avg_tasa, group = descripcion)) +
  geom_line(aes(color = descripcion), size = 1.5) +
  expand_limits(y = c(0, 6)) + 
  scale_y_continuous(breaks = c(0:6, 1)) +
  theme(legend.position = "top")

# Lineplot Avg Monto 2020
df_2020 %>% 
  group_by(Month, descripcion) %>% 
  summarise(avg_tasa = mean(tasa),
            avg_monto = mean(monto),
            sd_tasa = sd(tasa),
            .groups = "drop") %>% 
  ggplot(aes(Month, avg_monto, group = descripcion)) +
  geom_line(aes(color = descripcion), size = 1.5) +
  # expand_limits(y = c(0, 6)) + 
  scale_y_log10(labels = comma) +
  theme(legend.position = "top")


#Test for shiny

df_2020 %>% 
  group_by(Month, descripcion) %>% 
  summarise(avg_tasa = mean(tasa),
            .groups = "drop") %>% 
  ggplot(aes(Month, avg_tasa, group = descripcion, color = descripcion)) +
  geom_point() +
  geom_line()
```


Boxplots
```{r}

df_2020 %>% 
  ggplot(aes(y = tasa, x = Month, fill = Month)) +
  geom_boxplot() +
  #scale_y_log10() +
  theme(legend.position = "none") +
  labs(title = "2020") +
  facet_wrap(~descripcion)

df_2019 %>% 
  ggplot(aes(y = tasa, x = Month, fill = Month)) +
  geom_boxplot() +
  #scale_y_log10() +
  labs(title = "2019") +
  theme(legend.position = "none") +
  facet_wrap(~descripcion)


df_2021 %>% 
  ggplot(aes(y = tasa, x = Month, fill = Month)) +
  geom_boxplot() +
  #scale_y_log10() +
  labs(title = "2021") +
  theme(legend.position = "none") +
  facet_wrap(~descripcion)
```


Lag by Date
```{r}
df_2020 |>
  group_by(fechacorte, nombreentidad) |> 
  mutate(lag_tasa = tasa - lag(tasa, n =1, na.rm = T),
         lag_monto = monto - lag(monto, n = 1)) |>
  ungroup() |>
  ggplot(aes(fechacorte, lag_tasa)) +
  geom_point(size = 0.5, alpha = 0.4) +
  facet_wrap(~descripcion)

#Bancolombia
df_2020 %>% 
  filter(str_detect(nombreentidad, "Bancolombia")) %>% 
  group_by(fechacorte, descripcion) %>% 
  summarise(lag_tasa = tasa - lag(tasa, n = 1, order_by = descripcion)) %>%
  ungroup()

```



Scatterplots comparing 2019-2020

```{r}
# 
df_2020 %>% 
  select(-Year:-Wday) %>% 
  group_by(nombreentidad, descripcion) %>% 
  summarise(avg_tasa = mean(tasa),
            avg_monto = mean(monto),
            .groups = "drop") %>% 
  ggplot(aes(avg_tasa, avg_monto)) +
  geom_point(aes(color = descripcion), size = 3.5) +
  geom_vline(xintercept = mean(df_2020$tasa), alpha = 0.3) +
  geom_hline(yintercept = mean(df_2020$monto), alpha = 0.3) +
  scale_y_log10(labels = comma) +
  scale_x_continuous(breaks = c(0:7, 1)) +
  expand_limits(x = c(0, 7)) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
    labs(x = "Promedio Tasa de Captación por Entidad",
       y = "Promedio Monto en Pesos",
       title = "Relación Tasa de Captacion y Monto de los CDT en Colombia",
       subtitle = "Periodo 2020",
       caption = "Fuente: Tasas de interes de captacion y operaciones del mercado monetario. datos.gov.co") +
  theme(legend.position = "top",
        legend.title = element_blank()) 



df_2019$descripcion <- factor(df_2019$descripcion,
                         levels = c("A 30 Dias", "A 60 Dias", "A 90 Dias",
                                    "A 120 Dias", "A 180 Dias", "A 360 Dias"))


df_2019 %>% 
  select(-Year:-Wday) %>% 
  group_by(nombreentidad, descripcion) %>% 
  summarise(avg_tasa = mean(tasa),
            avg_monto = mean(monto),
            .groups = "drop") %>% 
  ggplot(aes(avg_tasa, avg_monto)) +
  geom_point(aes(color = descripcion), size = 3.5) +
  geom_vline(xintercept = mean(df_2019$tasa), alpha = 0.3) +
  geom_hline(yintercept = mean(df_2019$monto), alpha = 0.3) +
  scale_y_log10(labels = comma) +
  scale_x_continuous(breaks = c(0:7, 1)) +
  expand_limits(x = c(0, 7)) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  labs(x = "Promedio Tasa de Captación por Entidad",
       y = "Promedio Monto en Pesos",
       title = "Relación Tasa de Captacion y Monto de los CDT en Colombia",
       subtitle = "Periodo 2019",
       caption = "Fuente: Tasas de interes de captacion y operaciones del mercado monetario. datos.gov.co") +
  theme(legend.position = "top",
        legend.title = element_blank())
```


ggridges
```{r}
df_2020 %>% 
  filter(tasa <= 7, tasa > 0) %>%
  ggplot(aes(x = tasa, y = factor(Month, levels = rev(levels(factor(Month)))), fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "Tasa de Captación", option = "A", direction = -1,
                       guide = guide_colorbar(barwidth = unit(20, 'lines'),
                                              barheight = unit(2, 'lines'))) +
  scale_x_continuous(breaks = seq(0, 7, 1)) +
  coord_cartesian(expand = FALSE) +
  labs(title = "Tasas de Captacion CDT 2020",
       subtitle = "Cambio de Tasas de Captación durante el COVID19",
       caption = "Fuentes: datos.gov.co",
       x = "Tasa",
       y = "") +
  theme(legend.position = "none",
        legend.title = element_blank(),
        text = element_text(family = "Lato", size = 15),
        plot.margin = margin(12, 4, 25, 25))



df_2019 %>% 
  filter(tasa <= 7, tasa > 0) %>% 
  ggplot(aes(x = tasa, y = factor(Month, levels = rev(levels(factor(Month)))), fill = stat(x))) +
  geom_density_ridges_gradient(scale = 5, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "Tasa de Captación", option = "A", direction = -1,
                       guide = guide_colorbar(barwidth = unit(15, 'lines'),
                                              barheight = unit(2, 'lines'))) +
  scale_x_continuous(breaks = seq(0, 7, 1)) +
  labs(title = "Tasas de Captacion CDT 2019",
       x = "Tasa",
       y = "Mes") +
  theme_ridges() +
  theme(legend.position = "top",
        legend.title = element_blank(),
        text = element_text(family = "Source Sans Pro", size = 13),
        plot.title.position = "panel",
        plot.margin = margin(12, 25, 25, 0))




  # scale_fill_gradient2(low = "#2b83ba",
  #                      mid = "#ffffbf",
  #                      high = "#d7191c",
  #                      midpoint = median(df_dias_cdt$tasa),
  #                      guide = guide_colorbar(title.position = 'top',
  #                                           barwidth = unit(15, 'lines'),
  #                                           barheight = unit(2, 'lines'))) +
  # coord_cartesian(expand = FALSE) +
  # theme_minimal() +
  # theme(text = element_text(family = "Roboto", face = "bold", size = 13),
  #       legend.position = "top",
  #       plot.title.position = 'panel',
  #       plot.margin = margin(0, 25, 25, 0))
    
```



```{r}
clusters <- sample(unique(df_2020$descripcion), size = 6, replace = F)

cluster_sample <- df[df$descripcion %in% clusters, ]

table(cluster_sample$descripcion)


plot(df_2020$tasa~ df_2020$monto, data = df_2020)
with(df_2020, text(df_2020$tasa ~ df_2020$monto,
                   labels = df_2020$nombreentidad, pos = 4))
```

